name: Beyond the Developer
title: Beyond the Developer
description: I am Candykick, the Android, and iOS Developer.
tags:
  - blog
  - Android
  - iOS
  - Drawing
  - Develop
  - Programming
email: woo171tm@naver.com
disqus_username: 
show_hero: true